### ISSUE TITLE
Check for end position to be within genome size before calling view::slice

### ISSUE THREAD

**Issue by eseiler** [eseiler/SeqAn3_read_mapper#2]
https://github.com/eseiler/SeqAn3_read_mapper/blob/eb828a57b49a936ec7cd8f229d1688ea7bb7077f/mapper.cpp#L105

Maybe use something like
```cpp
auto database_view = genome | ranges::view::slice(position, std::min(position + query.size() + max_error, genome.size() - 1));
```

**Comment by marehr** [comment]
I would expect that slice does this by default. But, we should test it.

**Comment by eseiler** [comment]
I'll test it once I fix the other problem with the overflow

**Comment by eseiler** [comment]
it does
